sonar.projectKey=awsAmplify_doc_vault
sonar.projectName=doc_vault
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=server.js,server-with-presigned-urls.js,public
sonar.exclusions=node_modules/**,.agent/**,.scannerwork/**,coverage/**,**/*.min.js
